name: Bake an Image
on:
  push:

jobs:
  build-amd64:
    runs-on:
    - "self-hosted"
    - "linux"
    - "amd64"
    strategy:
      matrix:
        target: [ubuntu]
    outputs:
      metadata: ${{ steps.bake.outputs.metadata }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        uses: docker/bake-action@v1
        id: bake
        with:
          files: bake.hcl
          set: |
            *.platform=linux/amd64
          targets: ${{ matrix.target }}

  build-arm64:
    runs-on:
    - "self-hosted"
    - "linux"
    - "arm64"
    strategy:
      matrix:
        target: [ubuntu]
    outputs:
      metadata: ${{ steps.bake.outputs.metadata }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        uses: docker/bake-action@v1
        id: bake
        with:
          files: bake.hcl
          set: |
            *.platform=linux/arm64
          targets: ${{ matrix.target }}

  publish-manifest:
    runs-on: ubuntu-20.04
    needs: [build-amd64, build-arm64]
    steps:
      - name: Print build outputs
        run: |
          echo ${{ needs.build-amd64.outputs.metadata }}
          echo ${{ needs.build-arm64.outputs.metadata }}
